name: Nova Feature - Formulario
description: Formulario para criacao de nova feature no sistema.
title: "[Feature]: "
labels:
  - feature
  - triage
projects:
  - tech-challenge-17soat
assignees:
  - tech-challenge-17soat
type: feat

body:
  - type: markdown
    attributes:
      value: |

  - type: input
    id: Quem identificou a melhoria?
    attributes:
      label: Seu nome
      description: Q
      placeholder: "ex. Fulano de Tal."
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: Descreva a funcionalidade.
      description: Conte como espera que a funcionalidade aconteca.
      placeholder: Conte como espera que a funcionalidade aconteca.
      value: "Descreva.."
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Versão
      description: Qual versão do nosso software você está utilizando?
      options:
        - "Selecione"
        - "1.0.0"
        - "1.0.1"
        - "1.0.2"
        - "1.0.3"
        - "1.0.4"
        - "1.0.5"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: team
    attributes:
      label: Quem voce gostaria que realizasse essa atividade?
      multiple: true
      options:
        - Antonio
        - Joao
        - Lucas
        - Marcio
        - Pablo
  - type: textarea
    id: logs
    attributes:
      label: Encontrou algum problema?
      description: >-
        Copie e cole qualquer saída de log relevante. Ela será formatada
        automaticamente como código, portanto não é necessário utilizar crases.
      render: shell

  - type: upload
    id: screenshots
    attributes:
      label: Enviar capturas de tela
      description: >-
        Se aplicável, adicione capturas de tela para ajudar a explicar o problema.
    validations:
      required: false
